language: node_js

node_js:
  - "8"

services:
  - postgresql

install:
  - npm install

before_script:
  - psql -c 'create database more_recipes_test;' -U postgres
  - NODE_ENV=test ./node_modules/.bin/sequelize db:migrate

script:
  - npm test

after_success: npm run coveralls