export const UPDATE_UPVOTE_OPTIMISTICALLY = 'UPDATE_UPVOTE_OPTIMISTICALLY';
export const UPDATE_UPVOTE_REVERT = 'UPDATE_UPVOTE_REVERT';
export const UPDATE_DOWNVOTE_OPTIMISTICALLY = 'UPDATE_DOWNVOTE_OPTIMISTICALLY';
export const UPDATE_DOWNVOTE_REVERT = 'UPDATE_DOWNVOTE_REVERT';
export const UPDATE_FAVORITE_OPTIMISTICALLY = 'UPDATE_FAVORITE_OPTIMISTICALLY';
export const UPDATE_FAVORITE_REVERT = 'UPDATE_FAVORITE_REVERT';
